version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_database
      MYSQL_USER: haunguyen
      MYSQL_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: rails_database
      DB_PASSWORD: password
      DB_HOST: db
    stdin_open: true
    tty: true
